[connections.supabase]
SUPABASE_URL = "https://xngugcqehgyppqxuokyy.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZ3VnY3FlaGd5cHBxeHVva3l5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NTA3MTc0NSwiZXhwIjoyMDYwNjQ3NzQ1fQ.JjP6iQJwoMdhTDNb-N5rxCsEAHXJbDDvWvusTBQ754I"
